# Generated by Django 5.1.5 on 2025-02-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_rename_first_name_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='roles',
            new_name='role',
        ),
    ]
