# Generated by Django 5.1.5 on 2025-02-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='studnet',
            new_name='student',
        ),
    ]
